server:
  port: 8766
  tomcat:
    basedir: var/log/
    accesslog:
      enabled: true
      file-date-format: .yyyyMMdd
      prefix: access_log
      pattern: common

spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/userdb?serverTimezone=GMT
    username: clicknship-service-account
    password: ENC(VPMRfiU/TEhrsGmLO5SSbKyufVj0k4xGd/EmbnPITuIOsBY2TgSyt1gnZg4UToCV)
  jpa:
    show-sql: true
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}

jasypt:
    encryptor:
        password: R(G^YxGf*P:&u,76nh19$X3fhYsnV#R#tisFWXXe
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
      
feign:
  hystrix:
    enabled: true